### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by vanadium23** [coodict/javascript-in-one-pic#11]
Hello,
Can you make this picture available on github pages?
 https://pages.github.com/

**Comment by rainyear** [comment]
That's a good idea! SVG might be better for HTML to display.

**Comment by Frozenfire92** [comment]
+1 for SVG

**Comment by rainyear** [comment]
http://coodict.github.io/javascript-in-one-pic/ :beers::beers:

**Comment by vanadium23** [comment]
Thanks
