### ISSUE TITLE
Why not differ between Expressions, Statements and prototypes?

### ISSUE THREAD

**Issue by martensms** [coodict/javascript-in-one-pic#12]
I don't know if I like the representation of Objects and their data type categories. The issue I have in mind is mostly related to VM internals, such as Garbage Collection and memory allocation. For example, `var x = 3` will allocate runtime memory while `var x = new Number(3)` will allocate heap memory. Therefore, x must be cleared afterwards with the null trick or traced by the lifetime-GC.

Also, switch/case uses expressions, not statements. What does that mean? This is possible:

```javascript

var myvariable = 'somecontent';

switch(myvariable) {
    case (function() {
      console.log('expression!');
      return 'somecontent';
    })():
      console.log('It worked!');
    break;
}
```

Such things are really hard to show when focussing on data types, as pretty much everything in ECMA is related to the difference of expressions and statements.

**Comment by rainyear** [comment]
@martensms Very good point of view! Comparing to books I've read, organizing this map/nodes picture according to Object types or data types is more like K&R, it can be used as a structured manual(or syntax cheat sheet). While `Expressions, Statements` reminds me of SICP, they're more abstract concepts that might not be easily explained in a map/nodes picture, but they are also very important and fundamental concepts that beginner in programming should  be clear of, for example, I've found that a beginner to Js had difficulty understanding the difference between following lines:

```js
var p = {
  name: 'github',
};
var k = 'name';

p.k  // undefined
p.name // 'github'
p['name'] // 'github'
p[k] // 'github'
p['k'] // undefined
p[name]  // undefined
```

And it's extremely hard to explain the differences only according to this picture. The name of this project is `javascript in one pic` but it surely cannot(and will not) cover every corner of ECMA, VM memory allocation & GC will be shown in `Scope` or `Tips` or some other new nodes, if you have any idea about how to put the expressions & statements concepts into this picture, please let me know or make a pull request :pray:
