### ISSUE TITLE
Use a different example for parseInt("2.5").

### ISSUE THREAD

**Issue by Ucodia** [coodict/javascript-in-one-pic#16]
Using `parseInt("2.5");    // 2` as an example does not make it clear whether the interpreter floors or rounds the value.
As it will actually floor the value, using `parseInt("2.7");    // 2` will surely avoid any confusion.

**Comment by dmitry** [comment]
Make sure you always using `radix` argument with `parseInt`, normally you want `10`.

> If the input string begins with "0", radix is eight (octal) or 10 (decimal).  Exactly which radix is chosen is implementation-dependent.  ECMAScript 5 specifies that 10 (decimal) is used, but not all browsers support this yet.  For this reason always specify a radix when using parseInt.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt

**Comment by rainyear** [comment]
@dmitry :+1:  I'll add change this example!
