### ISSUE TITLE
A more informative README for the uninitiated 

### ISSUE THREAD

**Issue by aaronmyatt** [coodict/javascript-in-one-pic#20]
It would be fantastic to have a readme with more information related to the history, intent, creation and tools surrounding this project. Other projects of a similar nature would be of interest too.

Additionally, information regarding how one could go about replicating this project for another language would, personally, be wonderful!

Am I right in assuming this was the software used to generate the map: https://mindnode.com/ ? Judging purely by some of the file extensions.

**Comment by rainyear** [comment]
@aaronmyatt I'll try my best to improve it!

**Comment by aaronmyatt** [comment]
Please direct me to some reading material and i will gladly assist you.

**Comment by rainyear** [comment]
@aaronmyatt First, I'll write a new README in Chinese. I shared this project on reddit (http://www.reddit.com/r/javascript/comments/3ayrlb/learn_javascript_in_one_picture/) at first, you can find the discussions there. My original intent was to note down the syntax and basic concepts of languages I used in every day and never expected so much attention here. I'll keep working on the python3 & golang version, but other languages might just out of my reach.
