### ISSUE TITLE
Other languages-in-on-pic?

### ISSUE THREAD

**Issue by bucaran** [coodict/javascript-in-one-pic#24]
Amazing work, but when I looked at this what I thought was, _I would really like to have one for other languages too_! :laughing: 

Feel free to close this issue if you think it's off the scope, but maybe someone that knows can point to similar resources for other languages.

Regards

**Comment by rainyear** [comment]
@bucaran 
> README.md
> ## Releated projects
>
> - [Python3 in one pic](https://github.com/coodict/python3-in-one-pic)
> - Go in one pic (in preparation)

**Comment by bucaran** [comment]
@rainyear Thanks!
