### ISSUE TITLE
ES6 updates?

### ISSUE THREAD

**Issue by Rayraegah** [coodict/javascript-in-one-pic#25]
`var a = 1` is as global as `a = 1` private would be `let a = 1`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let

**Comment by rainyear** [comment]
I'm afraid ES6 should take another entire project, so let's try not to make it that complicated here.

**Comment by Rayraegah** [comment]
Welp, I'll get started on that then!

**Comment by rainyear** [comment]
@Rayraegah Just do it!
