### ISSUE TITLE
Horizontal alternative

### ISSUE THREAD

**Issue by MauJFernandez** [coodict/javascript-in-one-pic#26]
I know it's a bit of a pain to do it, but a horizontal version would be cool so we can print it and put it in the wall of our desks.

Awesome work, thank you.

**Comment by rainyear** [comment]
@MauJFernandez see #23 , there's a js in one pic.mm file exported in the project, it can be edited directly in [FreeMind](http://freemind.sourceforge.net/), maybe I should add this to the top of README.

**Comment by MauJFernandez** [comment]
@rainyear Great, thank you!
