### ISSUE TITLE
arguments are an array

### ISSUE THREAD

**Issue by temi** [coodict/javascript-in-one-pic#27]
Great stuff! I learned a few things.
I noticed you have written function's arguments variable as an object, but it is an Array.

**Comment by rainyear** [comment]
@temi 
> The arguments object is an Array-like object corresponding to the arguments passed to a function.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments

Actually there's no big difference, you can test the following lines:

```js
var fun = function(){
  console.log(arguments);
  console.log(typeof(arguments));
}
fun('hello', 'world');
// node v0.12.0
// { '0': 'hello', '1': 'world' }
// 'object'

// Chrome - Console
// ["hello", "world"]
// 'object'
```

**Comment by RangerMauve** [comment]
It's not actually an instance of Array. It's "array-like" It has a `length` property and properties that are numbers for each argument, but it doesn't have any of the methods that arrays have, for example, it doesn't have a `forEach()` method.

**Comment by temi** [comment]
I knew it as a special array. nodejs notation confused me. thanks!
