### ISSUE TITLE
identifiers -- key words -- instance

### ISSUE THREAD

**Issue by mjurczyk** [coodict/javascript-in-one-pic#5]
[contents.xml:573](https://github.com/coodict/javascript-in-one-pic/blob/master/js%20in%20one%20pic.mindnode/contents.xml#L573)

Shouldn't keyword `instance` be `instanceof` instead?

[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords)

**Comment by rainyear** [comment]
@mjurczyk I'll fix it, thx~
