### ISSUE TITLE
Colors not rendering in readme

### ISSUE THREAD

**Issue by josephgrossberg** [coodict/javascript-in-one-pic#8]
I see this, instead of brick-red and dark green text:

![screen shot 2015-06-26 at 1 06 57 pm](https://cloud.githubusercontent.com/assets/1637/8386336/5256e948-1c04-11e5-9544-414e057d40c6.png)

**Comment by rainyear** [comment]
@josephgrossberg I still can't figure out how can I render color in README.md, might need some help here!

**Comment by josephgrossberg** [comment]
Yeah, I don't think it's possible; maybe you can put images with those colors? Stuff I read said we can't do style attrs or tags in github markdown. :/

**Comment by josephgrossberg** [comment]
Anyhow, I really like this project, so I just wanted to add it to the issues in case someone knows a hack to get that working, with hex codes to colorize text.

**Comment by rainyear** [comment]
@josephgrossberg I use the very cooool badge project (http://shields.io/) to hack it for now, their badge images makes it more GITHUB at least :)

**Comment by josephgrossberg** [comment]
:+1:
